### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by rodneyrod** [matrix-hacks/adium-matrix#1]
Having this addon precompiled and available as a download from the Releases page would help a lot of users getting this working.

**Comment by kfatehi** [comment]
You're right. That said, there is at least the precompiled version in the repo here https://github.com/matrix-hacks/adium-matrix/tree/master/build/Debug

So if one downloads the repo as a Zip it would be there in the build folder.

**Comment by rodneyrod** [comment]
True, that solves that one.
